name: load-test-actions

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 252 jobs
        version: [10, 12, 14, 16, 18, 30]
        color: [blue, red, orange, green, red, yellow]
        food: [pizza, pasta, tacos, burgers, salad, sushi, cookies]

    steps:
      - uses: actions/checkout@v4

      - name: echo version
        run: echo ${{ matrix.version }}

      - name: echo color
        run: echo ${{ matrix.color }}

      - name: echo food
        run: echo ${{ matrix.food }}

      - name: create sample file
        run: truncate -s 10M foo

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: foo-${{ matrix.version }}-${{ matrix.color }}-${{ matrix.food }}
          path: foo
